from enum import Enum

class AgentName(str, Enum):
    CONVERSATION = "CONVERSATION_AGENT"
    RAG = "RAG_AGENT"
    WEB_SEARCH = "WEB_SEARCH_AGENT"
    INPUT_GUARDRAILS = "INPUT_GUARDRAILS"
    SCHEDULER = "SCHEDULER_AGENT"
