services:
  backend:
    # If you're building locally instead of using a pre-built image
    build:
      context: ./backend
      target: production
    # Or use your pre-built image:
    # image: ghcr.io/yourorg/backend:${VERSION:-latest}
    env_file:
      - ./backend/.env.production
    environment:
      - APP_ENV=production
    depends_on: [db]
    restart: unless-stopped
    ports: ["8000:8000"]

  frontend:
    build:
      context: ./frontend          # Dockerfile we finalised earlier
    env_file: ./frontend/.env.production
    depends_on: [backend]
    restart: unless-stopped
    ports: ["3000:3000"]

include:
  - compose.base.yml
