services:
  ollama:
    image: ollama/ollama:latest
    command: ["serve"]
    ports:
      - "11434:11434"
    volumes:
      - "/mnt/c/Users/Adam/.ollama/models:/root/.ollama/models:ro"

  web:
    build:
      context: ./backend     # ← here
      dockerfile: Dockerfile # optional if your Dockerfile is named "Dockerfile"
    env_file:
      - ./backend/.env.development
    environment:
      OLLAMA_HOST: ollama
      OLLAMA_PORT: 11434
    ports:
      - "8000:8000"
    depends_on:
      - ollama

volumes:
  ollama_models:
