services:
  db:
    image: pgvector/pgvector:pg14
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 2326
      POSTGRES_DB: postgres
    volumes:
      - db-data:/var/lib/postgresql/data
      - ./docker/db/initdb.d:/docker-entrypoint-initdb.d
    ports: ["5432:5432"]

volumes:
  db-data:
