services:
  db:
    image: postgres:14-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 2326
      POSTGRES_DB: postgres
    volumes:
      - db-data:/var/lib/postgresql/data
    ports: ["5432:5432"]

  tavily-mcp:
      image: mcp/tavily:latest          # official image you referenced
      command: >
        tavily-mcp
        http
        --host 0.0.0.0
        --port 8080
      environment:
        TAVILY_API_KEY: ${TAVILY_API_KEY}   # export in your shell / CI
      restart: unless-stopped


  scheduler-mcp:
    build:
      context: ./backend
      dockerfile: Dockerfile
    command: >
      uvicorn app.mcp_servers.scheduler.server:app
      --host 0.0.0.0 --port 5210 --workers 1
    environment:
      DATABASE_URL: postgresql+asyncpg://postgres:2326@db:5432/postgres
    depends_on: [db]
    restart: unless-stopped

volumes:
  db-data:
